### ISSUE TITLE
No entities and Configuration Problem after Update from 24.12.02 to 24.12.04

### ISSUE THREAD

**Issue by Summer-of69** [davidrapan/ha-solarman#283]
### Description

Hi David!
Today i updated from 12/24/02 to 12/24/04 and now have a configuration error. I use the deye_sg04lp3.yaml.
What is the problem or where can I view the logs?

### Reproduction Steps

Update from 24.12.02 to 24.12.04

### Log

Where can i get the LogFile?

### Version

v24.12.04

**Comment by Summer-of69** [comment]
![Problem](https://github.com/user-attachments/assets/b1df5919-2514-43c5-a1ca-3859633712e7)

**Comment by sisasimon** [comment]
+1 I have the same issue

**Comment by sisasimon** [comment]
> ### Log
> Where can i get the LogFile?

I guess under Settings > System > Logs

**Comment by MikealSouth** [comment]
+1, same issue for me
```
Logger: homeassistant.config_entries
Source: config_entries.py:983
First occurred: 11:49:00 (1 occurrences)
Last logged: 11:49:00

Error migrating entry balcony_solar for solarman
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 983, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/__init__.py", line 125, in async_migrate_entry
    del new_options[CONF_BATTERY_NOMINAL_VOLTAGE]
        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'battery_nominal_voltage'
```

**Comment by davidrapan** [comment]
Hi, thanks for report, I'll fix it promptly. 😉

**Comment by davidrapan** [comment]
@KFAcapital, would you be willing to provide full log (debug one would be best) cause your problem is little bit different... unless HA just don't care about failed migrations and just starts to load the device anyway...

**Comment by Summer-of69** [comment]
> Hi, thanks for report, I'll fix it promptly. 👍
> 
> Edit: In the meantime, those who can (do not have any edits or adjustments to the original sensors) can delete and re-add device in that version and it will work. 😉

Thanks for the quick response. Deleting device and adding it back worked for me! 👍

**Comment by davidrapan** [comment]
When comes to migrations it's really tricky but I believe [fix: Config entry migration](https://github.com/davidrapan/ha-solarman/commit/6f0afbe2f9aec6aecee1737ae4d04728d396e4f5) should solve the issue.

**Comment by davidrapan** [comment]
What version of HA are you running?

**Comment by gardiol** [comment]
Yes same issue here, delete and add again fixed the issue quickly.

**Comment by vinste** [comment]
Hi, 
Migration from 24.12.02 to 24.12.06 still fails. Normal?

```
Enregistreur: homeassistant.config_entries
Source: config_entries.py:983
S'est produit pour la première fois: 19:44:48 (3 occurrences)
Dernier enregistrement: 19:44:48

Error migrating entry onduleur for solarman
Error migrating entry Garage for solarman
Error migrating entry Abris for solarman
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 983, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/__init__.py", line 85, in async_migrate_entry
    bulk_migrate(new_options.setdefault(CONF_ADDITIONAL_OPTIONS, {}), new_options, CONF_BATTERY_NOMINAL_VOLTAGE, CONF_BATTERY_LIFE_CYCLE_RATING)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bulk_migrate() takes 3 positional arguments but 4 were given
```

**Comment by davidrapan** [comment]
Ah crap, that should have been method called `bulk_inherit` and not `bulk_migrate` in that single case on line 85. 🤯

**Comment by vinste** [comment]
Hi,
With 24.12.06_2, I now have following error: 

```
Enregistreur: homeassistant.config_entries
Source: config_entries.py:640
S'est produit pour la première fois: 21:38:00 (5 occurrences)
Dernier enregistrement: 21:40:39

Error setting up entry onduleur for solarman
Error setting up entry Garage for solarman
Error setting up entry Abris for solarman
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/__init__.py", line 29, in async_setup_entry
    coordinator = InverterCoordinator(hass, Inverter(config, await EndPointProvider(config).discover()))
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/provider.py", line 88, in discover
    if self.ipaddress.is_private and (discover := await InverterDiscovery(self.hass, self.host, self.serial).discover()):
                                                                                                ^^^^^^^^^^^
  File "/config/custom_components/solarman/provider.py", line 70, in __getattr__
    return getattr(self.config, attr)
  File "src/propcache/_helpers_c.pyx", line 80, in propcache._helpers_c.cached_property.__get__
  File "/config/custom_components/solarman/provider.py", line 42, in serial
    return protected(self.config_entry.data.get(CONF_SERIAL), "Configuration parameter [serial] does not have a value")
  File "/config/custom_components/solarman/common.py", line 22, in protected
    raise vol.Invalid(error)
voluptuous.error.Invalid: Configuration parameter [serial] does not have a value

```
Any clue?

**Comment by davidrapan** [comment]
Migrations did not run for some reason (re-adding the device will solve it).

**Comment by vinste** [comment]
I tried to reconfigure the device, but serial number does not show up in the configuration panel, and without it, the configuration fails.
I would not like to delete and recreate the inverter as I fear I will loose all my automations based on current entities ids.
Do you think there would be a way to migrate without deletion/re-creation?

**Comment by davidrapan** [comment]
You can edit `/homeassistant/.storage/core.config_entries` and inject the configuration item. Find your device (search for term solarman or your inverter name) and either rename "inverter_serial" to "serial" if it's still there or add next to the name of your device (right behind ",") `"serial": 9874561230,` (your device serial of course).

But if you did not directly edit entity_ids of the sensors you will not lose anything by re-adding the device.

**Comment by vinste** [comment]
Migration now works from 24.12.02 to 24.1.06_3, thanks a lot!

**Comment by berndlin** [comment]
I'm getting _Setup failed for custom integration 'solarman': Unable to import component: No module named 'propcache'_ with any of the v24.12.06 releases
[home-assistant_2024-12-07T10-45-50.693Z.log](https://github.com/user-attachments/files/18048029/home-assistant_2024-12-07T10-45-50.693Z.log)

**Comment by vinste** [comment]
You might consider installing the last version HA, it seems solved in 2024.11.1

**Comment by davidrapan** [comment]
Hi @berndlin, `ha core rebuild` could also help. If you already are on the most recent HA Core version then downgrade and upgrade of the core component will also help.

**Comment by berndlin** [comment]
Good morning,

can confirm that updating the HA image from 2024.10 to 2024.11.3 fixed the missing package, and the migration is now also working as expected.

Thanks guys!
