### ISSUE TITLE
Sofar: Incorrect energy values

### ISSUE THREAD

**Issue by jandeuss** [davidrapan/ha-solarman#424]
### Description

Hello,

since the update of the last 2024 version, some entities are repeatedly shown as unknown or have insanely high values ​​that the energy panel in home assistant is not working correctly.

This affects Sofar hyd 10K inverters with the lse-3 ethernet logger.

Perhaps a check can be built in to ensure that the generation values ​​cannot be 2,000,000 W in 5 minutes. or a battery charge / discharge of 150,000 W in 5 minutes.

This should be intercepted.

Thank you

### Reproduction Steps

the problem comes many times a day 

### Log

![Image](https://github.com/user-attachments/assets/887ec4f4-ee0d-410f-be10-34d3008d7560)

### Version

25.02.12

### Home Assistant Core Version

2025.2.4

### Home Assistant Operating System Version

14.2

**Comment by jandeuss** [comment]
another example....

![Image](https://github.com/user-attachments/assets/5ca72153-1156-46b8-82f4-a43c14bbdc5c)

**Comment by davidrapan** [comment]
Hi @jandeuss, can you please provide debug log? Thank you.

**Comment by rromrrom** [comment]
![Image](https://github.com/user-attachments/assets/182499a2-7ada-4073-b313-5ebbe7d63df3)

![Image](https://github.com/user-attachments/assets/6e916006-74fe-4f99-b6b7-9185f224d2f7)

Full DEBUG log in attachment

[home-assistant.log](https://github.com/user-attachments/files/19116605/home-assistant.log)

**Comment by davidrapan** [comment]
I'm sorry but it's incomplete log (missing integration debug messages for some reason).

**Comment by davidrapan** [comment]
It looks like that the issue is coming from reading of fragmented modbus responses which is proly the same issue as in #426

**Comment by davidrapan** [comment]
[fix: Add detection of modbus response fragmentation](https://github.com/davidrapan/ha-solarman/commit/714dbc66c69a343471203267f8a8c64871f51a65)

**Comment by davidrapan** [comment]
Hi @rromrrom, the log file is missing messages from the integration and only contains debug messages from pymodbus. I need full log to be able to determine what's wrong....

**Comment by rromrrom** [comment]
what is logs from the integration and where should I find/enable those?

**Comment by rromrrom** [comment]
@davidrapan I will play with a logging settings. Please tell me what particular log example should I see to understand it shows what you are looking for? Thanks.

**Comment by rromrrom** [comment]
https://drive.google.com/file/d/1e0jhwl-cqPLx_mXGS2QPORfKNwIcMLGZ/view?usp=sharing

Now log has some more info, please take a look. Thanks.

**Comment by rromrrom** [comment]
done:  https://drive.google.com/file/d/16oDX8naxnwl8b0AF_UltQFx0wyT5gFNc/view?usp=sharing

**Comment by davidrapan** [comment]
Are you sure you are running the latest version of the integration? This has been fixed in [v25.03.12_1](https://github.com/davidrapan/ha-solarman/releases/tag/v25.03.12_1)

**Comment by rromrrom** [comment]
![Image](https://github.com/user-attachments/assets/afcbea96-2870-4070-9a22-6f6452c3b736)

Yes, I'm sure

**Comment by davidrapan** [comment]
No you are not this is [v25.03.12](https://github.com/davidrapan/ha-solarman/releases/tag/v25.03.12) and you need [v25.03.12_1](https://github.com/davidrapan/ha-solarman/releases/tag/v25.03.12_1)

**Comment by rromrrom** [comment]
Hm, I just manually re-downloaded latest version. And it is updated to 25.03.12_1 , not sure why it is required manual action.  Anyway, thanks for the help, appreciate that. Will check how it works more.

**Comment by rromrrom** [comment]
@davidrapan  25.03.12_1 works in general, but original issue with weird spikes on chart doesn't solved. Periodically I still see some huge numbers.

**Comment by rromrrom** [comment]
![Image](https://github.com/user-attachments/assets/fd86d1c7-5083-4a60-a443-e31a6e36ed80)

**Comment by rromrrom** [comment]
![Image](https://github.com/user-attachments/assets/07a01ec2-952a-4c82-ae0d-cb548f4585b3)

**Comment by davidrapan** [comment]
It seems that the problem is not only related to this integration, but others have similar problems with corrupted data... Try incorporating the changes from [fix: Add PV Power validation according to max rated power for Deye](https://github.com/davidrapan/ha-solarman/commit/192857150c17d7f03390a35eba8ba92b6ef3fadd)

**Comment by rromrrom** [comment]
I will try that. Thanks.
One more note for the history: I have 2 inverters, same model. One is branded as Deye, another one as TAB, but technically they are same device from same manufacturer. The both have same firmware version.
- First one works without any issues. No weird numbers on charts or other issues.
- Second one - sometimes has connection issues and it is only one who has issues with huge numbers. Integration itself looks fully functional and I see no other issues except than statistics distorsion on energy chart which is coming from one device only.

**Comment by as-cmi** [comment]
@rromrrom are your inverters connected on the same modbus-rtu line? 
Check this, maybe it can help: #423 
(I have not yet updated the inverter firmware.. how to do it?)

**Comment by rromrrom** [comment]
@as-cmi not sure about how to answer on your question properly. My inverters doesn't use anything like waveshare. They are both connected through wifi/ethernet loggers from deye.

**Comment by davidrapan** [comment]
@rromrrom, you can actually connect multiple modbus slave devices even to the stick logger (that's what @as-cmi was referring to), but I'm sure your inverters each have their own logger. 😉

**Comment by rromrrom** [comment]
correct, I have 2 separate loggers

**Comment by rromrrom** [comment]
Well, I have 25.03.16 and original issue is still happens.

**Comment by davidrapan** [comment]
I'll need new debug log. 😉

**Comment by rromrrom** [comment]
https://drive.google.com/file/d/1tvISQ8Ligq18QXvnbu6bj5UUsFkqcrPG/view?usp=sharing

**Comment by davidrapan** [comment]
And around what ~time any issues occurred?

**Comment by rromrrom** [comment]
<img width="296" alt="Image" src="https://github.com/user-attachments/assets/867a468e-84f2-474f-8e70-0f83254e087e" />
UTC+2

**Comment by rromrrom** [comment]
<img width="995" alt="Image" src="https://github.com/user-attachments/assets/57308178-ebc7-4b82-be48-9b7eba2a471e" />

**Comment by rromrrom** [comment]
<img width="1823" alt="Image" src="https://github.com/user-attachments/assets/fb120f0e-974f-4433-8866-c11b7ae74182" />

**Comment by davidrapan** [comment]
I can see the issue.

**Comment by davidrapan** [comment]
[fix: Add transaction identifier validation for ethernet loggers](https://github.com/davidrapan/ha-solarman/commit/6e89c84a65877aaa213953cd9f01b74398e2ab79)

**Comment by rromrrom** [comment]
thanks! testing...

**Comment by as-cmi** [comment]
![Screenshot_2025-03-20-10-19-35-359_io.homeassistant.companion.android~2.jpg](https://github.com/user-attachments/assets/daa99c3a-92d0-489b-96ed-37ae896d10ba)

It seems the problem is not yet solved.. the only version working fine for me was the 24.12.22.

**Comment by rromrrom** [comment]
My setup shows zero spikes since upgrade to 25.03.18. 
The only thing is a bit weird I have 2 entities in unkonw state for this invertor, while they are not unknown for another one. But I'm not sure it it is related to this particulat topic.

<img width="294" alt="Image" src="https://github.com/user-attachments/assets/7fb8e848-8042-415d-b5c3-4f6795b3052a" />

**Comment by rromrrom** [comment]
@davidrapan Thanks for the fix. Now integration way more better works for me.

**Comment by davidrapan** [comment]
Total sensors have validation set to numbers `> 0.1` so whenever is the value lower it rather show Unknown. It's a failsafe because some devices when they restart cycle all sensors trough zeroes which would also generate spikes in the HA. 😉

**Comment by as-cmi** [comment]
@coserotondo I have 25.03.18 and I'm experiencing spikes every now and then.. With 24.12.22 worked like a charm.
Others say it's ok, maybe I'm doing something wrong.. I have a wired setup with modbus-rtu to tcp converter.
Now I'm updating the inverter but i don't think it'll make difference.
